GET http://localhost:4000/subscribers

###

GET http://localhost:4000/subscribers/60f8a0d1b0c1a93014924c1d

###

POST http://localhost:4000/subscribers
Content-Type:  application/json

{
    "name": "jhon",
    "email": "jhon@jhon",
    "phone": "09990332",
    "message": "sdfhasdf"
}

###

DELETE http://localhost:4000/subscribers/60f8a0d1b0c1a93014924c1d


###

PATCH http://localhost:4000/subscribers/60f896f7facff24c74b23c1e
Content-Type:  application/json

{
    "email": "berdugo"
}